export const projects = [
  {
    id: "police-simulator",
    label: { de: "Spiel", en: "Game" },
    title: "Police Simulator: Patrol Officers",
    description: {
      de: [
        "Willkommen in Brighton! Schließe dich den Reihen der Polizei dieser fiktiven US-amerikanischen Großstadt an und erlebe den Alltag eines Streifenpolizisten oder einer Streifenpolizistin. Beginne mit Parkverstößen und arbeite dich nach oben, um mehr Verantwortung zu übernehmen. Werde Teil der Stadtgemeinschaft von Brighton, lerne deine Nachbarschaft kennen, erfülle während deiner Schicht deine alltäglichen Pflichten und bekämpfe die Kriminalität.",
        "Sei hart, aber fair: Auch du selbst solltest stets das Gesetz achten! Sammle in jeder Schicht wertvolle Erfahrungen und schalte so weitere Nachbarschaften, Stadtteile und Aufgaben frei!",
        "Police Simulator: Patrol Officers bietet ein dynamisches Verkehrssystem, das den Verkehrsfluss sowie Autounfälle und andere Notfälle, die sich während deiner Schicht zufällig ereignen können, organisch erschafft. Sei also jederzeit darauf vorbereitet, schnell und angemessen zu reagieren! Erlebe die offene Welt von Brighton, in der du die Nachbarschaft wählen kannst, die du während deines Streifendienstes sichern möchtest. Fahre Streife in drei einzigartigen Stadtteilen, die jeweils mehrere Nachbarschaften umfassen. Jede Nachbarschaft versprüht ein einzigartiges Flair, von den Wolkenkratzern in Downtown bis hin zum historischen Stadtteil Brickston. Das Intuitionssystem ermöglicht es dir, bei der Befragung von Zeugen wichtige Hinweise zu sammeln, und kann dir helfen, Situationen sofort zu lösen – du solltest also stets auf alles achten, was um dich herum gesagt und getan wird. Deine Pflichten sind deine Verantwortung!",
        "Durch Fortschritt und Freischalten neuer Stadtteile werden auch neue Pflichten hinzugefügt. Beginne damit, Strafzettel auszustellen, sei jedoch auch bereit, Unfälle abzuwickeln, die sich direkt vor deinen Augen ereignen können! In dieser belebten und brodelnden Stadt erwarten dich die verschiedensten Aufgaben. Unterbinde den Drogenhandel im örtlichen Park, liefere dir Verfolgungsjagden mit Graffiti-Sprayern, die illegal Wände besprühen, halte Raser mit Blaulicht an und sichere Unfallstellen mit Straßenabsperrungen und Pylonen ab. Sei auf alles vorbereitet – von kleineren Vorfällen wie einem Fahrzeug, das eine Bushaltestelle blockiert, bis hin zur Verhaftung von Verdächtigen und deren Verbringung in die Haftzellen. Deine Pflichten sind deine Verantwortung!",
        "Police Simulator: Patrol Officers bietet einen Simulations-Modus für erfahrene Spieler, die ein möglichst authentisches Spielerlebnis suchen, sowie einen Vereinfachten Modus für alle, die eine etwas entspanntere Streife durch die Straßen von Brighton vorziehen.",
      ],
      en: [
        "Welcome to Brighton! Join the ranks of this fictitious American city's police force and experience the everyday life of a police officer. Begin with parking violations and work your way up to shouldering greater responsibilities. Be part of Brighton's community, get to know your neighborhood, and fulfill the daily duties of a police officer as you fight crime during your shift. Always be tough, but fair: respect the law and gain more experience to unlock more neighborhoods, districts, and duties!",
        "Police Simulator: Patrol Officers includes a dynamic traffic system that organically creates traffic flows and car accidents, as well as emergency situations that randomly pop up during your shifts. Be ready to respond at a moment’s notice! Enter the open world of Brighton, where you can choose which neighborhoods you patrol and keep safe. Patrol three unique districts, each home to several neighborhoods. Each one has a distinct flair: from the high rises of downtown to the historical buildings of Brickston. The Intuition System allows you to pick up on important clues when interrogating witnesses and can help you resolve situations immediately – so make sure you're always paying attention to everything being said and done. Your duties are your responsibility!",
        "Progressing and unlocking new districts also adds new duties. Begin by issuing tickets, but be ready to handle accidents that can happen right in front of your eyes! Many different duties are waiting to be encountered in this living and breathing city. Stop drug deals from taking place in the local park, chase graffiti sprayers illegally tagging walls, stop speeding cars with your police siren, and even set up road barriers and cones around traffic accidents. Be prepared for anything – from minor incidents like a car blocking a bus stop to having to apprehend suspects and taking them to the holding cells. Your duties are your responsibility! Police Simulator: Patrol Officers offers a Simulation Mode for veteran players looking for the most authentic experience, as well as a Casual Mode for players who want a more relaxing patrol around the streets of Brighton.",
      ],
    },
    coverArt: "/images/police-simulator.jpeg",
    coverArtAlt: "Police Simulator: Patrol Officers Cover Art",
    video: "/videos/police-simulator.mp4",
    programmingLanguages: ["C++"],
    software: ["Unreal Engine 4"],
    date: "2021-2024",
    roles: { de: ["Programmierung"], en: ["Programming"] },
    developer: "Aesir Interactive",
    publisher: "astragon Entertainment",
    link: {
      de: "https://patrol-officers.com/de-DE",
      en: "https://patrol-officers.com/",
    },
    images: [
      "/images/police-simulator/img01.jpg",
      "/images/police-simulator/img02.jpg",
      "/images/police-simulator/img03.jpeg",
      "/images/police-simulator/img04.jpg",
      "/images/police-simulator/img05.webp",
      "/images/police-simulator/img06.webp",
      "/images/police-simulator/img07.webp",
      "/images/police-simulator/img08.webp",
    ],
  },
  {
    id: "eternitys-lair",
    label: { de: "Spiel", en: "Game" },
    title: "Eternity's Lair",
    subtitle: {
      de: "Let me tell you a story...",
      en: "Let me tell you a story...",
    },
    description: {
      de: [
        "Im Action Rogue-Like Eternity's Lair kämpft sich der Space Samurai Alex durch Horden von schrecklichen Kreaturen auf einer verlassenen Raumstation.",
        "Alex kommt mit seinem Raumschiff auf einer vermeintlich verlassenen Raumstation an. Allerdings ist sie nicht so verlassen, wie sie scheint. Als er den Aufzug verlässt, wird er von Eternity's Schergen, kybernetisch augmentierte Monsterratten, angegriffen. Dank seiner herausragenden Geschwindigkeit und atemberaubenden Schwertkunst ist er bestens für die Kämpfe gewappnet. Doch eigenartige Ereignisse beeinflussen seine Reise und je weiter Alex in die Station vordringt, desto stärker werden die Schergen.",
        "Kann Alex die nötige Ausrüstung finden, um sich Eternity zu stellen?",
        "Entwickelt wurde Eternity's Lair im Rahmen der Projektarbeit im Studiengang Informatik - Game Engineering im Sommersemester 2022. Das Projekt betreute Prof. Dr. René Bühling.",
      ],
      en: [
        "In the action roguelike Eternity's Lair space samurai Alex fights its way through hordes of terrifying creatures on an abandoned space station.",
        "Alex arrives with their spaceship at a supposedly abandoned space station. However, it is not as abandoned as it seems. As they exit the elevator, they are attacked by Eternity's minions, cybernetically augmented monster rats. Thanks to their outstanding speed and breathtaking swordsmanship, they are well prepared for the battles. But strange events affect their journey and the further Alex advances into the station, the stronger the minions become.",
        "Can Alex find the necessary equipment to face Eternity?",
        "Eternity's Lair was developed as part of a Computer Science - Game Engineering course at Kempten University of Applied Sciences in the summer semester of 2022. The project was supervised by Prof. Dr. René Bühling.",
      ],
    },
    coverArt: "/images/eternitys-lair.jpg",
    coverArtAlt: "Eternity's Lair Cover Art",
    video: "/videos/eternitys-lair.mp4",
    programmingLanguages: ["C#"],
    software: ["Unity", "Adobe Illustrator", "Blender"],
    date: "2022",
    roles: {
      de: ["Programmierung", "UI", "Projektorganisation"],
      en: ["Programming", "UI", "Project Organization"],
    },
    link: {
      de: "https://theparadoxis.itch.io/eternitys-lair",
      en: "https://theparadoxis.itch.io/eternitys-lair",
    },
    images: [
      "/images/eternitys-lair/img01.jpg",
      "/images/eternitys-lair/img02.jpg",
      "/images/eternitys-lair/img03.jpg",
      "/images/eternitys-lair/img04.jpg",
    ],
  },
  {
    id: "adventure-island",
    label: { de: "Spiel", en: "Game" },
    title: "Adventure Island",
    subtitle: { de: "Herbst", en: "Autumn" },
    description: {
      de: [
        `Adventure Island ist ein exploratives Adventurespiel in Egoperspektive im Stil von "Quern" und "The Witness". Das Spiel setzt sich aus vier Inseln zusammen, die über Portale miteinander verbunden sind und jeweils eine Jahreszeit darstellen. Hierbei war ich hauptsächlich an der Entwicklung der Herbstinsel beteiligt.`,
        "Auf der Herbstinsel können Spieler in eine Welt voller Magie eintauchen und vier Elemente nutzen, um herausfordernde Rätsel in der bunten Jahreszeit Herbst zu lösen.",
        "Frisch auf der Herbstinsel angekommen, muss der Spieler die Kraft des Windes nutzen, um eine Schlucht zu überwinden und den Weg in das Dorf zu öffnen. Dort warten zwei weitere herausfordernde Rätsel auf ihn. Das Eine ein feuriges Erlebnis und das Andere eine schockierende Erfahrung. Falls er die Herausforderung meistert, darf er nicht wasserscheu sein, um die fehlenden Schlüssel zu erlangen. Diese nutzt er, um ein antikes Portal zu erreichen und damit in die nächste Jahreszeit zu schreiten.",
      ],
      en: [
        `Adventure Island is an explorative adventure game in first-person perspective in the style of "Quern" and "The Witness". The game consists of four islands, which are connected via portals and each represent a season. I was mainly involved in the development of Autumn Island.`,
        "On Autumn Island, players can immerse themselves in a world full of magic and use four elements to solve challenging puzzles in the colorful world of autumn.",
        "Freshly arrived on Autumn Island, players must use the power of the wind to overcome a ravine and open the way to the village. There, two more challenging puzzles await them. One a fiery experience and the other a shocking one. If they master the challenge, they must not be afraid of water in order to obtain the missing keys. They use these to reach an ancient portal and thus step into the next season.",
      ],
    },
    coverArt: "/images/adventure-island.png",
    coverArtAlt: "Adventure Island Cover Art",
    video: "/videos/adventure-island.mp4",
    programmingLanguages: ["C#"],
    software: ["Blender", "Unity"],
    date: "2020-2021",
    contributors: [
      "Florian Brauner",
      "Paul Hagedorn",
      "Fabian Juppe",
      "Kilian Raab",
    ],
    music: "Lukas Satzger",
    sounds: "Eva Sibbe",
    roles: {
      de: [
        "Animationen",
        "Blitzrätsel",
        "Design & Idee",
        "Interaktion",
        "Inventar",
        "Items",
        "Leveldesign",
        "Modellierung",
        "Portale",
        "Postprocessing",
        "Projektorganisation",
        "Sound & Musik Implementation",
        "Support",
        "Trailer",
        "VFX",
      ],
      en: [
        "Animations",
        "Design & Idea",
        "Interaction",
        "Inventory",
        "Items",
        "Level Design",
        "Lightning Puzzle",
        "Modeling",
        "Portals",
        "Post-Processing",
        "Project Organization",
        "Sound & Music Implementation",
        "Support",
        "Trailer",
        "VFX",
      ],
    },
    github: "https://github.com/fabianjuppe/adventure-island",
    images: [
      "/images/adventure-island/img01.png",
      "/images/adventure-island/img02.png",
      "/images/adventure-island/img03.png",
      "/images/adventure-island/img04.png",
      "/images/adventure-island/img05.png",
      "/images/adventure-island/img06.png",
      "/images/adventure-island/img07.png",
      "/images/adventure-island/img08.png",
      "/images/adventure-island/img09.png",
      "/images/adventure-island/img10.png",
      "/images/adventure-island/img11.png",
      "/images/adventure-island/img12.png",
      "/images/adventure-island/img13.png",
      "/images/adventure-island/img14.png",
      "/images/adventure-island/img15.png",
      "/images/adventure-island/img16.png",
    ],
  },
  {
    id: "wonderland",
    label: { de: "Spiel", en: "Game" },
    title: "Wonderland",
    description: {
      de: [
        "Wonderland ist ein Adventurespiel in Egoperspektive. Der Spieler muss vier Säulen in die richtige Position bringen, um aus einer Pyramide zu entkommen.",
        "Das Spiel wurde mit einem Szenegraphen für Qt von Prof. Dr. Bernd Dreier erstellt.",
      ],
      en: [
        "Wonderland is an adventure game in first-person perspective. The player must put four pillars in the right position to escape from a pyramid.",
        "The game was created with a scene graph for Qt by Prof. Dr. Bernd Dreier.",
      ],
    },
    coverArt: "/images/wonderland.png",
    coverArtAlt: "Wonderland Cover Art",
    video: "/videos/wonderland.mp4",
    programmingLanguages: ["C++", "OpenGL"],
    software: ["Qt"],
    date: "2020-2021",
    contributors: [
      "Florian Brauner",
      "Paul Hagedorn",
      "Fabian Juppe",
      "Lea Kuznik",
    ],
    sounds: "Eva Sibbe",
    roles: { de: ["Programmierung"], en: ["Programming"] },
    github: "https://github.com/fabianjuppe/wonderland",
    images: [
      "/images/wonderland/img01.png",
      "/images/wonderland/img02.png",
      "/images/wonderland/img03.png",
      "/images/wonderland/img04.png",
    ],
  },
  {
    id: "space-shooter",
    label: { de: "Spiel", en: "Game" },
    title: "Space Shooter",
    description: {
      de: [
        "In Space Shooter steuert der Spieler ein Raumschiff, welches Raketen abfeuern kann.",
        "Das Spiel wurde in zwei Versionen erstellt.",
      ],
      en: [
        "In Space Shooter the player controls a spaceship that can fire missiles.",
        "The game was created in two versions.",
      ],
    },
    coverArt: "/images/space-shooter.png",
    coverArtAlt: "Space Shooter Cover Art",
    programmingLanguages: ["C++", "C#"],
    software: ["Vektoria", "Unity"],
    date: "2020",
    contributors: ["Fabian Juppe"],
    github: "https://github.com/fabianjuppe/space-shooter",

    vektoria: {
      title: "Vektoria",
      coverArt: "/images/space-shooter/img02.png",
      coverArtAlt: "Space Shooter Vektoria Cover Art",
      programmingLanguages: ["C++"],
      software: ["Vektoria"],
      date: "2020",
      contributors: ["Fabian Juppe"],
      description: {
        de: [
          "Die erste Version des Spiels wurde mit der Vektoria Engine von Prof. Dr. Tobias Breiner in C++ erstellt.",
        ],
        en: [
          "The first version of the game was created with the Vektoria Engine by Prof. Dr. Tobias Breiner in C++.",
        ],
      },
      images: [
        "/images/space-shooter/img07.png",
        "/images/space-shooter/img08.png",
        "/images/space-shooter/img09.png",
        "/images/space-shooter/img10.png",
      ],
    },

    unity: {
      title: "Unity",
      coverArt: "/images/space-shooter/img01.png",
      coverArtAlt: "Space Shooter Unity Cover Art",
      programmingLanguages: ["C#"],
      software: ["Unity"],
      date: "2020",
      contributors: ["Fabian Juppe"],
      description: {
        de: [
          "Eine zweite Version des Spiels wurde mit Unity erstellt. Außerdem wurde ein lokaler Mehrspielermodus ergänzt, in welchem sich die Spieler gegenseitig zerstören können.",
        ],
        en: [
          "A second version of the game was created using Unity. Also, a local multiplayer mode was added, in which players can destroy each other.",
        ],
      },
      images: [
        "/images/space-shooter/img03.png",
        "/images/space-shooter/img04.png",
        "/images/space-shooter/img05.png",
        "/images/space-shooter/img06.png",
      ],
    },
  },
  {
    id: "bond-of-life",
    label: { de: "Game Design Dokument", en: "Game Design Document" },
    title: "Bond of Life",
    subtitle: {
      de: "Balance zwischen Mensch und Maschine",
      en: "Balance between Humand and Machine",
    },
    description: {
      de: [
        "Die Protagonistin Alice erwacht viele Jahre nach ihrem Tod in einem Roboterkörper. Künstliche Intelligenz hat in einem Krieg nahezu die gesamte Menschheit ausgelöscht. Nun ist es ihre Aufgabe, die letzten überlebenden Menschen zu retten, ohne dabei weder ihre Menschlichkeit noch ihren Verstand zu verlieren.",
      ],
      en: [
        "The protagonist Alice awakens in a robot body many years after her death. Artificial intelligence has wiped out almost all of humanity in a war. Now it is her task to save the last surviving humans without losing either her humanity or her sanity.",
      ],
    },
    coverArt: "/images/bond-of-life.png",
    coverArtAlt: "Bond of Life Cover Art",
    date: "2020",
    contributors: ["Fabian Juppe"],
    pdf: {
      de: "/bond-of-life/bond-of-life-de.pdf",
      en: "/bond-of-life/bond-of-life-en.pdf",
    },
  },
  {
    id: "floating-island",
    label: { de: "Kurzfilm", en: "Short Film" },
    title: "Floating Island",
    description: {
      de: [
        "Floating Island ist ein in Blender erstellter Kurzfilm. Die Insel wurde selbstständig modelliert und texturiert.",
      ],
      en: [
        "Floating Island ist a short film created in Blender. The island was modeled and textured independently.",
      ],
    },
    coverArt: "/images/floating-island.png",
    coverArtAlt: "Floating Island Cover Art",
    video: "/videos/floating-island.mp4",
    software: ["Blender"],
    date: "2019-2020",
    contributors: ["Paul Hagedorn", "Fabian Juppe"],
    images: [
      "/images/floating-island/img01.png",
      "/images/floating-island/img02.png",
      "/images/floating-island/img03.png",
      "/images/floating-island/img04.png",
    ],
  },
];
