export const projects = [
  {
    id: "police-simulator",
    label: "Spiel",
    title: "Police Simulator: Patrol Officers",
    description: [
      "Willkommen in Brighton! Schließe dich den Reihen der Polizei dieser fiktiven US-amerikanischen Großstadt an und erlebe den Alltag eines Streifenpolizisten oder einer Streifenpolizistin. Beginne mit Parkverstößen und arbeite dich nach oben, um mehr Verantwortung zu übernehmen. Werde Teil der Stadtgemeinschaft von Brighton, lerne deine Nachbarschaft kennen, erfülle während deiner Schicht deine alltäglichen Pflichten und bekämpfe die Kriminalität.",
      "Sei hart, aber fair: Auch du selbst solltest stets das Gesetz achten! Sammle in jeder Schicht wertvolle Erfahrungen und schalte so weitere Nachbarschaften, Stadtteile und Aufgaben frei!",
      "Police Simulator: Patrol Officers bietet ein dynamisches Verkehrssystem, das den Verkehrsfluss sowie Autounfälle und andere Notfälle, die sich während deiner Schicht zufällig ereignen können, organisch erschafft. Sei also jederzeit darauf vorbereitet, schnell und angemessen zu reagieren! Erlebe die offene Welt von Brighton, in der du die Nachbarschaft wählen kannst, die du während deines Streifendienstes sichern möchtest. Fahre Streife in drei einzigartigen Stadtteilen, die jeweils mehrere Nachbarschaften umfassen. Jede Nachbarschaft versprüht ein einzigartiges Flair, von den Wolkenkratzern in Downtown bis hin zum historischen Stadtteil Brickston. Das Intuitionssystem ermöglicht es dir, bei der Befragung von Zeugen wichtige Hinweise zu sammeln, und kann dir helfen, Situationen sofort zu lösen – du solltest also stets auf alles achten, was um dich herum gesagt und getan wird. Deine Pflichten sind deine Verantwortung!",
      "Durch Fortschritt und Freischalten neuer Stadtteile werden auch neue Pflichten hinzugefügt. Beginne damit, Strafzettel auszustellen, sei jedoch auch bereit, Unfälle abzuwickeln, die sich direkt vor deinen Augen ereignen können! In dieser belebten und brodelnden Stadt erwarten dich die verschiedensten Aufgaben. Unterbinde den Drogenhandel im örtlichen Park, liefere dir Verfolgungsjagden mit Graffiti-Sprayern, die illegal Wände besprühen, halte Raser mit Blaulicht an und sichere Unfallstellen mit Straßenabsperrungen und Pylonen ab. Sei auf alles vorbereitet – von kleineren Vorfällen wie einem Fahrzeug, das eine Bushaltestelle blockiert, bis hin zur Verhaftung von Verdächtigen und deren Verbringung in die Haftzellen. Deine Pflichten sind deine Verantwortung!",
      "Police Simulator: Patrol Officers bietet einen Simulations-Modus für erfahrene Spieler, die ein möglichst authentisches Spielerlebnis suchen, sowie einen Vereinfachten Modus für alle, die eine etwas entspanntere Streife durch die Straßen von Brighton vorziehen.",
    ],
    coverArt: "/images/police-simulator.jpeg",
    coverArtAlt: "Police Simulator: Patrol Officers Cover Art",
    video: "/videos/police-simulator.mp4",
    programmingLanguages: ["C++"],
    software: ["Unreal Engine 4"],
    date: "2021-2024",
    roles: ["Programmierung"],
    developer: "Aesir Interactive",
    publisher: "astragon Entertainment",
    link: "https://patrol-officers.com/de-DE",
    images: [
      "/images/police-simulator/img01.jpg",
      "/images/police-simulator/img02.jpg",
      "/images/police-simulator/img03.jpeg",
      "/images/police-simulator/img04.jpg",
      "/images/police-simulator/img05.webp",
      "/images/police-simulator/img06.webp",
      "/images/police-simulator/img07.webp",
      "/images/police-simulator/img08.webp",
    ],
  },
  {
    id: "eternitys-lair",
    label: "Spiel",
    title: "Eternity's Lair",
    subtitle: "Let me tell you a story...",
    description: [
      "Im Action Rogue-Like Eternity's Lair kämpft sich der Space Samurai Alex durch Horden von schrecklichen Kreaturen auf einer verlassenen Raumstation.",
      "Alex kommt mit seinem Raumschiff auf einer vermeintlich verlassenen Raumstation an. Allerdings ist sie nicht so verlassen, wie sie scheint. Als er den Aufzug verlässt, wird er von Eternity's Schergen, kybernetisch augmentierte Monsterratten, angegriffen. Dank seiner herausragenden Geschwindigkeit und atemberaubenden Schwertkunst ist er bestens für die Kämpfe gewappnet. Doch eigenartige Ereignisse beeinflussen seine Reise und je weiter Alex in die Station vordringt, desto stärker werden die Schergen.",
      "Kann Alex die nötige Ausrüstung finden, um sich Eternity zu stellen?",
      "Entwickelt wurde Eternity's Lair im Rahmen der Projektarbeit im Studiengang Informatik - Game Engineering im Sommersemester 2022. Das Projekt betreute Prof. Dr. René Bühling.",
    ],
    coverArt: "/images/eternitys-lair.jpg",
    coverArtAlt: "Eternity's Lair Cover Art",
    video: "/videos/eternitys-lair.mp4",
    programmingLanguages: ["C#"],
    software: ["Unity", "Adobe Illustrator", "Blender"],
    date: "2022",
    roles: ["Programmierung", "UI", "Projektorganisation"],
    link: "https://theparadoxis.itch.io/eternitys-lair",
    images: [
      "/images/eternitys-lair/img01.jpg",
      "/images/eternitys-lair/img02.jpg",
      "/images/eternitys-lair/img03.jpg",
      "/images/eternitys-lair/img04.jpg",
    ],
  },
  {
    id: "adventure-island",
    label: "Spiel",
    title: "Adventure Island",
    subtitle: "Herbst",
    description: [
      `Adventure Island ist ein exploratives Adventurespiel in Egoperspektive im Stil von "Quern" und "The Witness". Das Spiel setzt sich aus vier Inseln zusammen, die über Portale miteinander verbunden sind und jeweils eine Jahreszeit darstellen. Hierbei war ich hauptsächlich an der Entwicklung der Herbstinsel beteiligt.`,
      "Auf der Herbstinsel können Spieler in eine Welt voller Magie eintauchen und vier Elemente nutzen, um herausfordernde Rätsel in der bunten Jahreszeit Herbst zu lösen.",
      "Frisch auf der Herbstinsel angekommen, muss der Spieler die Kraft des Windes nutzen, um eine Schlucht zu überwinden und den Weg in das Dorf zu öffnen. Dort warten zwei weitere herausfordernde Rätsel auf ihn. Das Eine ein feuriges Erlebnis und das Andere eine schockierende Erfahrung. Falls er die Herausforderung meistert, darf er nicht wasserscheu sein, um die fehlenden Schlüssel zu erlangen. Diese nutzt er, um ein antikes Portal zu erreichen und damit in die nächste Jahreszeit zu schreiten.",
    ],
    coverArt: "/images/adventure-island.png",
    coverArtAlt: "Adventure Island Cover Art",
    video: "/videos/adventure-island.mp4",
    programmingLanguages: ["C#"],
    software: ["Blender", "Unity"],
    date: "2020-2021",
    contributors: [
      "Florian Brauner",
      "Paul Hagedorn",
      "Fabian Juppe",
      "Kilian Raab",
    ],
    music: "Lukas Satzger",
    sounds: "Eva Sibbe",
    roles: [
      "Animationen",
      "Blitzrätsel",
      "Design & Idee",
      "Interaktion",
      "Inventar",
      "Items",
      "Leveldesign",
      "Modellierung",
      "Portale",
      "Postprocessing",
      "Projektorganisation",
      "Sound & Musik Implementation",
      "Support",
      "Trailer",
      "VFX",
    ],
    github: "https://github.com/fabianjuppe/adventure-island",
    images: [
      "/images/adventure-island/img01.png",
      "/images/adventure-island/img02.png",
      "/images/adventure-island/img03.png",
      "/images/adventure-island/img04.png",
      "/images/adventure-island/img05.png",
      "/images/adventure-island/img06.png",
      "/images/adventure-island/img07.png",
      "/images/adventure-island/img08.png",
      "/images/adventure-island/img09.png",
      "/images/adventure-island/img10.png",
      "/images/adventure-island/img11.png",
      "/images/adventure-island/img12.png",
      "/images/adventure-island/img13.png",
      "/images/adventure-island/img14.png",
      "/images/adventure-island/img15.png",
      "/images/adventure-island/img16.png",
    ],
  },
  {
    id: "wonderland",
    label: "Spiel",
    title: "Wonderland",
    description: [
      "Wonderland ist ein Adventurespiel in Egoperspektive. Der Spieler muss vier Säulen in die richtige Position bringen, um aus einer Pyramide zu entkommen.",
      "Das Spiel wurde mit einem Szenegraphen für Qt von Prof. Dr. Bernd Dreier erstellt.",
    ],
    coverArt: "/images/wonderland.png",
    coverArtAlt: "Wonderland Cover Art",
    video: "/videos/wonderland.mp4",
    programmingLanguages: ["C++", "OpenGL"],
    software: ["Qt"],
    date: "2020-2021",
    contributors: [
      "Florian Brauner",
      "Paul Hagedorn",
      "Fabian Juppe",
      "Lea Kuznik",
    ],
    sounds: "Eva Sibbe",
    roles: ["Programmierung"],
    github: "https://github.com/fabianjuppe/wonderland",
    images: [
      "/images/wonderland/img01.png",
      "/images/wonderland/img02.png",
      "/images/wonderland/img03.png",
      "/images/wonderland/img04.png",
    ],
  },
  {
    id: "space-shooter",
    label: "Spiel",
    title: "Space Shooter",
    description: [
      "In Space Shooter steuert der Spieler ein Raumschiff, welches Raketen abfeuern kann.",
      "Das Spiel wurde in zwei Versionen erstellt.",
    ],
    coverArt: "/images/space-shooter.png",
    coverArtAlt: "Space Shooter Cover Art",
    programmingLanguages: ["C++", "C#"],
    software: ["Vektoria", "Unity"],
    date: "2020",
    contributors: ["Fabian Juppe"],
    github: "https://github.com/fabianjuppe/space-shooter",

    vektoria: {
      title: "Vektoria",
      coverArt: "/images/space-shooter/img02.png",
      coverArtAlt: "Space Shooter Vektoria Cover Art",
      programmingLanguages: ["C++"],
      software: ["Vektoria"],
      date: "2020",
      contributors: ["Fabian Juppe"],
      description: [
        "Die erste Version des Spiels wurde mit der Vektoria Engine von Prof. Dr. Tobias Breiner in C++ erstellt.",
      ],
      images: [
        "/images/space-shooter/img07.png",
        "/images/space-shooter/img08.png",
        "/images/space-shooter/img09.png",
        "/images/space-shooter/img10.png",
      ],
    },

    unity: {
      title: "Unity",
      coverArt: "/images/space-shooter/img01.png",
      coverArtAlt: "Space Shooter Unity Cover Art",
      programmingLanguages: ["C#"],
      software: ["Unity"],
      date: "2020",
      contributors: ["Fabian Juppe"],
      description: [
        "Eine zweite Version des Spiels wurde mit Unity erstellt. Außerdem wurde ein lokaler Mehrspielermodus ergänzt, in welchem sich die Spieler gegenseitig zerstören können.",
      ],
      images: [
        "/images/space-shooter/img03.png",
        "/images/space-shooter/img04.png",
        "/images/space-shooter/img05.png",
        "/images/space-shooter/img06.png",
      ],
    },
  },
  {
    id: "bond-of-life",
    label: "Game Design Dokument",
    title: "Bond of Life",
    subtitle: "Balance zwischen Mensch und Maschine",
    description: [
      "Bond of Life setzt sich aus zwei Kapiteln zusammen.",
      "Im ersten Kapitel ist es ein Rätselspiel und im zweiten Kapitel ein Schleich-Shooter.",
      "Die Protagonistin Alice erwacht viele Jahre nach ihrem Tod in einem Roboterkörper. Künstliche Intelligenz hat in einem Krieg nahezu die gesamte Menschheit ausgelöscht. Nun ist es ihre Aufgabe, die letzten überlebenden Menschen zu retten, ohne dabei weder ihre Menschlichkeit noch ihren Verstand zu verlieren.",
    ],
    coverArt: "/images/bond-of-life.png",
    coverArtAlt: "Bond of Life Cover Art",
    date: "2020",
    contributors: ["Fabian Juppe"],
    link: "/bond-of-life/bond-of-life-de.pdf",
  },
  {
    id: "floating-island",
    label: "Kurzfilm",
    title: "Floating Island",
    description: [
      "Floating Island ist ein in Blender erstellter Kurzfilm. Die Insel wurde selbstständig modelliert und texturiert.",
    ],
    coverArt: "/images/floating-island.png",
    coverArtAlt: "Floating Island Cover Art",
    video: "/videos/floating-island.mp4",
    software: ["Blender"],
    date: "2019-2020",
    contributors: ["Paul Hagedorn", "Fabian Juppe"],
    images: [
      "/images/floating-island/img01.png",
      "/images/floating-island/img02.png",
      "/images/floating-island/img03.png",
      "/images/floating-island/img04.png",
    ],
  },
];
